export const EMAILJS_CONFIG = {
  SERVICE_ID: process.env.VITE_EMAILJS_SERVICE_ID,
  TEMPLATE_ID: process.env.VITE_EMAILJS_CONTACT_TEMPLATE_ID,
  NEWSLETTER_TEMPLATE_ID: process.env.VITE_EMAILJS_NEWSLETTER_TEMPLATE_ID,
  PUBLIC_KEY: process.env.VITE_EMAILJS_PUBLIC_KEY,
};